language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - pip install pipenv
  - pip install mixer
  - pipenv install --skip-lock 
before_script:
  - psql -c 'create database myDiary_test;' -U postgres
  - python manage.py migrate
script:
  - coverage run --source='myDiary_API' manage.py test && coverage report
after_success:
  - coveralls
